// Official Confirmed & Waiting List Teams from ISIH Results PDF
// M. H. Saboo Siddik College of Engineering - ACM Student Chapter

export const SIH_CONFIRMED_DATA = [
  {
    srNo: 1,
    teamName: "HackHive",
    mentor: "Ashfaque",
    category: "Software",
    psId: "SIH26165",
    hostOrg: "Oil India Limited",
    problemStatement: "AI/NLP Engine to Detect Serious Injury & Fatality (SIF) Precursors in OIL's Unsafe-Act/Unsafe-Condition and Near-Miss Reports",
    leaderName: "Momin Faizan Gufran Ahmad",
    rollNo: "241732",
    email: "faizan.241732.cs@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 2,
    teamName: "JAN-DRISHTI",
    mentor: "Fiza shaikh",
    category: "Software",
    psId: "26102",
    hostOrg: "MoSPI",
    problemStatement: "Development of an AI-powered system to detect anomalies, fraud, and inefficiencies in MPLAD Scheme implementation regd.",
    leaderName: "AYAN SHAMIM KHAN",
    rollNo: "241804",
    email: "shamim.241804.ci@mhssce.ac.in",
    branch: "Computer Science & Engineering (IoT)",
    status: "Confirmed",
  },
  {
    srNo: 3,
    teamName: "Paradox",
    mentor: "Er. Farzana Khan",
    category: "Software",
    psId: "SIH26017",
    hostOrg: "Ministry of Rural Development",
    problemStatement: "Predictive Analytics System for Early Detection of Land Acquisition Delays",
    leaderName: "Simra Khan",
    rollNo: "252468",
    email: "simra.252668.it@mhssce.ac.in",
    branch: "Information Technology",
    status: "Confirmed",
  },
  {
    srNo: 4,
    teamName: "HEXATRACK",
    mentor: "Prof. Shrinidhi Gindi",
    category: "Hardware",
    psId: "SIH26222",
    hostOrg: "AICTE",
    problemStatement: "Student Innovation - SRLMS - Smart Railway Linen Lifecycle Management System",
    leaderName: "ABIZER SAIFY",
    rollNo: "231401",
    email: "abizer.231401.it@mhssce.ac.in",
    branch: "Information Technology",
    status: "Confirmed",
  },
  {
    srNo: 5,
    teamName: "GG",
    mentor: "Dr. Chaitali Mahajan, Er. Awij Alam",
    category: "Hardware",
    psId: "SIH26004",
    hostOrg: "Ministry of Development of North Eastern Region (MDoNER)",
    problemStatement: "AI-Assisted Early Detection System for Osteoarthritis (OA) Risk Markers in North Eastern Region (NER)",
    leaderName: "Khan Moinuddin Jamal Ahmed",
    rollNo: "241624",
    email: "moinuddin.241624.et@mhssce.ac.in",
    branch: "Electronics & Telecommunication Engineering",
    status: "Confirmed",
  },
  {
    srNo: 6,
    teamName: "NexGen",
    mentor: "Prof. Amar Pawade",
    category: "Software",
    psId: "26196",
    hostOrg: "AICTE",
    problemStatement: "Student Innovation - Ideas that can boost fitness activities and assist in keeping fit.",
    leaderName: "Ansari Abdullah Mohd. Adil",
    rollNo: "231703",
    email: "abdullah.231703.cs@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 7,
    teamName: "Griot",
    mentor: "Ashfaque Shaikh",
    category: "Software",
    psId: "SIH26104",
    hostOrg: "All India Council for Technical Education (AICTE)",
    problemStatement: "AI-Powered Real-Time Detection and Prevention of Voice Cloning Impersonation Attacks",
    leaderName: "SHAIKH MOHD AASIM UBAIDUR REHMAN",
    rollNo: "231751",
    email: "aasim.231751.cs@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 8,
    teamName: "Ouroboros",
    mentor: "Ashfaque Shaikh",
    category: "Software",
    psId: "SIH26053",
    hostOrg: "DRDO",
    problemStatement: "Adaptive Variable Resolution 2.5D Lidar Mapping for Dynamic Environment Perception",
    leaderName: "Shaikh Eshaan Samir",
    rollNo: "231747",
    email: "eshaan.231747.cs@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 9,
    teamName: "Quantum Crew",
    mentor: "Dr. Amol Sankpal",
    category: "Software",
    psId: "SIH26147",
    hostOrg: "National Technical Research Organisation (NTRO)",
    problemStatement: "Automated model for analysis of .IQ and .wav files along with signal parameter extraction",
    leaderName: "Shaikh Farukh",
    rollNo: "231629",
    email: "farukh.231629.et@mhssce.ac.in",
    branch: "Electronics & Telecommunication Engineering",
    status: "Confirmed",
  },
  {
    srNo: 10,
    teamName: "CodeX Worriors",
    mentor: "Mohd Ashfaque Shaikh CSE(AIML)",
    category: "Software",
    psId: "SIH26189",
    hostOrg: "Ministry of Home Affairs",
    problemStatement: "AI-Powered Criminal Network Analysis System",
    leaderName: "FAHD NAKHWA",
    rollNo: "251305",
    email: "fahd.251305.co@mhssce.ac.in",
    branch: "Computer Engineering",
    status: "Confirmed",
  },
  {
    srNo: 11,
    teamName: "PacketMinds",
    mentor: "Ghazala Khan",
    category: "Software",
    psId: "SIH26153",
    hostOrg: "National Technical Research Organisation (NTRO)",
    problemStatement: "AI based Network Attack Forecasting from Network Traffic Data",
    leaderName: "Patel Mohammed Amin Kaifi",
    rollNo: "241829",
    email: "amin.241829.ci@mhssce.ac.in",
    branch: "Computer Science & Engineering (IoT)",
    status: "Confirmed",
  },
  {
    srNo: 12,
    teamName: "IMMORTALS",
    mentor: "Zainab Mirza, Fardeen Shaikh",
    category: "Software",
    psId: "SIH26127",
    hostOrg: "Bharat Electronics Limited",
    problemStatement: "City-Wide AI Engine for Multi-Camera ANPR Trajectory Tracking and Urban Traffic Analytics",
    leaderName: "Aariz Sheikh",
    rollNo: "231453",
    email: "aariz.231453.it@mhssce.ac.in",
    branch: "Information Technology",
    status: "Confirmed",
  },
  {
    srNo: 13,
    teamName: "Echelon",
    mentor: "Rasheed Khan",
    category: "Software",
    psId: "SIH26190",
    hostOrg: "Ministry of Home Affairs",
    problemStatement: "Secure Digital Document Management System for Legal and Investigation Documents",
    leaderName: "Ayman Sajid Halai",
    rollNo: "251409",
    email: "ayman.251409.it@mhssce.ac.in",
    branch: "Information Technology",
    status: "Confirmed",
  },
  {
    srNo: 14,
    teamName: "RaiNova",
    mentor: "Dr. Chaitali Mahajan",
    category: "Software",
    psId: "26085",
    hostOrg: "Ministry of Earth Sciences (MoES)",
    problemStatement: "Urban Flood Nowcasting System (Drainage and Rainfall Coupling)",
    leaderName: "Sayed Azib Arif",
    rollNo: "241741",
    email: "azib.241741.cs@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 15,
    teamName: "Team Rocket",
    mentor: "Nabanita Nath Chowdhury",
    category: "Hardware",
    psId: "26112",
    hostOrg: "Autodesk",
    problemStatement: "Design and Develop a Modular Autonomous Mobile Robot (AMR) Platform Smart Warehouse Automation",
    leaderName: "Ansari Mohd Azhad",
    rollNo: "241206",
    email: "azhad.241206.co@mhssce.ac.in",
    branch: "Computer Engineering",
    status: "Confirmed",
  },
  {
    srNo: 16,
    teamName: "NeuroForge",
    mentor: "Dr. Zainab Mirza",
    category: "Software",
    psId: "26047",
    hostOrg: "Ministry of Ayush",
    problemStatement: "Patient Case-Taking Software",
    leaderName: "Siddiqui Tabish Javed",
    rollNo: "231456",
    email: "tabish.231456.it@mhssce.ac.in",
    branch: "Information Technology",
    status: "Confirmed",
  },
  {
    srNo: 17,
    teamName: "Hackathon Hunters",
    mentor: "Ashfaque Sir",
    category: "Software",
    psId: "SIH26076",
    hostOrg: "Ministry of Earth Sciences (MoES)",
    problemStatement: "Develop a personalized home page for 'Mausam' mobile application.",
    leaderName: "Rehan Naeem Ansari",
    rollNo: "251316",
    email: "rehan.251316.co@mhssce.ac.in",
    branch: "Computer Engineering",
    status: "Confirmed",
  },
  {
    srNo: 18,
    teamName: "E-CORP",
    mentor: "Zainab Mirza, Fardeen Shaikh",
    category: "Software",
    psId: "SIH26101",
    hostOrg: "MoSPI",
    problemStatement: "Develop an AI enabled learning platform that identifies competency gaps, recommends personalized training through integration with the iGOT Karmayogi ecosystem, and capable of generating Quizzes and Multiple choice questions (MCQs) from uploaded learning materials to strengthen capacity building in India's Official Statistical System.",
    leaderName: "Wahid Patel",
    rollNo: "231439",
    email: "wahid.231439.it@mhssce.ac.in",
    branch: "Information Technology",
    status: "Confirmed",
  },
  {
    srNo: 19,
    teamName: "LogicLoom",
    mentor: "Sana Shaikh",
    category: "Software",
    psId: "SIH26125",
    hostOrg: "Bharat Electronics Limited",
    problemStatement: "Blockchain-Based Secure Platform for Identity, Access Control, and Digital Asset Management",
    leaderName: "Shadab Sayyed",
    rollNo: "231445",
    email: "shadab.231445.it@mhssce.ac.in",
    branch: "Information Technology",
    status: "Confirmed",
  },
  {
    srNo: 20,
    teamName: "SEAQUENCE",
    mentor: "Prof. Arshi Khan",
    category: "Software",
    psId: "SIH26143",
    hostOrg: "National Technical Research Organisation (NTRO)",
    problemStatement: "Leveraging satellite imagery to determine Oil spills at sea along with AIS data correlations to identify vessel responsible for the spill.",
    leaderName: "Khan Arif Shamsulhaque",
    rollNo: "231718",
    email: "arif.231718.cs@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 21,
    teamName: "AgriNova",
    mentor: "Chaitali Mahajan",
    category: "Software",
    psId: "SIH26131",
    hostOrg: "Government of Maharashtra",
    problemStatement: "Early detection and management of crop diseases and pest infestations",
    leaderName: "MEMON AFSHEEN MOHAMMAD ISHAQUE",
    rollNo: "251521",
    email: "afsheen.251521.et@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 22,
    teamName: "CipherWraiths",
    mentor: "Khan Ghazala",
    category: "Software",
    psId: "SIH26159",
    hostOrg: "National Technical Research Organisation (NTRO)",
    problemStatement: "SecureMailScope: AI-Assisted Cryptographic Security Posture Assessment for Secure Email Communications",
    leaderName: "Sayyed Abuzar",
    rollNo: "241836",
    email: "abuzar.241836.ci@mhssce.ac.in",
    branch: "Computer Science & Engineering (IoT)",
    status: "Confirmed",
  },
  {
    srNo: 23,
    teamName: "AUTOSYNC",
    mentor: "Prof. Farheen Bobere",
    category: "Hardware",
    psId: "26203",
    hostOrg: "AICTE",
    problemStatement: "Student Innovation - Creating intelligent devices to improve commutation sector.",
    leaderName: "Dhanraj Ashok Ambekar",
    rollNo: "241301",
    email: "dhanraj.241301.ae@mhssce.ac.in",
    branch: "Mechanical Engineering Automobile",
    status: "Confirmed",
  },
  {
    srNo: 24,
    teamName: "Team VitalBeats",
    mentor: "Asst. Prof. Ahlam Ansari",
    category: "Hardware",
    psId: "SIH26215",
    hostOrg: "AICTE",
    problemStatement: "Student Innovation",
    leaderName: "Hannan Ravish Shemle",
    rollNo: "231211",
    email: "hannan.231211.co@mhssce.ac.in",
    branch: "Computer Engineering",
    status: "Confirmed",
  },
  {
    srNo: 25,
    teamName: "Coder Janta Party (CJP)",
    mentor: "Ghazala Khan",
    category: "Software",
    psId: "SIH26104",
    hostOrg: "All India Council for Technical Education (AICTE)",
    problemStatement: "AI-Powered Real-Time Detection and Prevention of Voice Cloning Impersonation Attacks",
    leaderName: "Annam Kazi",
    rollNo: "241812",
    email: "annam.241812.ci@mhssce.ac.in",
    branch: "Computer Science & Engineering (IoT)",
    status: "Confirmed",
  },
  {
    srNo: 26,
    teamName: "HTTPS:Sentinel",
    mentor: "Dr. Zainab Mirza",
    category: "Software",
    psId: "SIH26228",
    hostOrg: "Ministry of Defence (MoD)",
    problemStatement: "Trustworthy Computer Vision Integrity Assurance for Data, Models and Inference Outputs in Multi-Contributor Pipelines",
    leaderName: "Shaikh Shifa Irshad Ahmad",
    rollNo: "241459",
    email: "shifa.241459.it@mhssce.ac.in",
    branch: "Information Technology",
    status: "Confirmed",
  },
  {
    srNo: 27,
    teamName: "CodeX",
    mentor: "Prof. Amar Pawade",
    category: "Software",
    psId: "SIH26202",
    hostOrg: "AICTE",
    problemStatement: "Student Innovation - Ideas focused on the intelligent use of resources for transforming and advancements of technology with combining artificial intelligence to explore more various sources and get valuable insights.",
    leaderName: "ANSARI ABDULLAH MOHAMMED ADIL",
    rollNo: "231703",
    email: "abdullah.231703.cs@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 28,
    teamName: "WhiteBox",
    mentor: "Mohd Ashfaque Mohd Haroon Shaikh",
    category: "Software",
    psId: "SIH26170",
    hostOrg: "Indian Space Research Organisation (ISRO)",
    problemStatement: "AI-Driven Anomaly Detection in Component Burn-In & Screening",
    leaderName: "Khan Mohammad Anas Raza",
    rollNo: "241723",
    email: "anasraza.241723.cs@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 29,
    teamName: "BlueVector",
    mentor: "Dr. Ashfaq Shaikh",
    category: "Software",
    psId: "SIH26143",
    hostOrg: "National Technical Research Organisation (NTRO)",
    problemStatement: "Leveraging satellite imagery to determine Oil spills at sea along with AIS data correlations to identify vessel responsible for the spill.",
    leaderName: "Shujaat Ali Punjani",
    rollNo: "241242",
    email: "shujaat.241242.co@mhssce.ac.in",
    branch: "Computer Engineering",
    status: "Confirmed",
  },
  {
    srNo: 30,
    teamName: "The DOMinators",
    mentor: "Ahlam Ansari",
    category: "Software",
    psId: "SIH26171",
    hostOrg: "Indian Space Research Organisation (ISRO)",
    problemStatement: "On-device Visual Perception for Light-weight Browser Agents",
    leaderName: "Huzefa Attar",
    rollNo: "241208",
    email: "huzefa.241208.co@mhssce.ac.in",
    branch: "Computer Engineering",
    status: "Confirmed",
  },
  {
    srNo: 31,
    teamName: "SENTRY",
    mentor: "Chaitali Mahajan",
    category: "Software",
    psId: "26187",
    hostOrg: "Ministry of Home Affairs",
    problemStatement: "AI-Based Intelligent Video Analytics Platform for Border Surveillance using existing CCTV Infrastructure.",
    leaderName: "Shaikh Umme Hani Mohd. Shahid",
    rollNo: "242776",
    email: "ummehani.242776.aiml@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 32,
    teamName: "Recursed",
    mentor: "Prof. Asadullah Shaikh",
    category: "Software",
    psId: "SIH26207",
    hostOrg: "AICTE",
    problemStatement: "Student Innovation - Smart education, a concept that describes learning in digital age. It enables learners to learn more effectively, efficiently, flexibly and comfortably.",
    leaderName: "Hammad Siddique",
    rollNo: "241257",
    email: "hammad.241257.co@mhssce.ac.in",
    branch: "Computer Engineering",
    status: "Confirmed",
  },
  {
    srNo: 33,
    teamName: "Grid guardians",
    mentor: "Pragati Pal",
    category: "Software",
    psId: "SIH26028",
    hostOrg: "Ministry of Railways",
    problemStatement: "AI-Powered Passenger Digital Twin & Dynamic ETA Engine for Real-Time Crowd Management and Operations Balancing in Mumbai Suburban Network",
    leaderName: "Khan Mohd Ruman Mohd Amir",
    rollNo: "251916",
    email: "ruman.251916.ci@mhssce.ac.in",
    branch: "Computer Science & Engineering (IoT)",
    status: "Confirmed",
  },
  {
    srNo: 34,
    teamName: "Dev X",
    mentor: "Dr. Tarannum Shaikh",
    category: "Software",
    psId: "SIH26047",
    hostOrg: "Ministry of Ayush",
    problemStatement: "Patient Case-Taking Software",
    leaderName: "Azmi Rayyan Sharib",
    rollNo: "231706",
    email: "rayyan.231706.cs@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 35,
    teamName: "TechDivaS",
    mentor: "Sana Mam",
    category: "Software",
    psId: "SIH26204",
    hostOrg: "AICTE",
    problemStatement: "Student Innovation - A solution/idea that can boost the current situation of the tourism industries including hotels, travel and others.",
    leaderName: "Shaikh Fatma Nasiruddin",
    rollNo: "251440",
    email: "fatma.251440.it@mhssce.ac.in",
    branch: "Information Technology",
    status: "Confirmed",
  },
  {
    srNo: 36,
    teamName: "TERRASHIELD",
    mentor: "Arshi Khan",
    category: "Software",
    psId: "26001",
    hostOrg: "Ministry of Development of North Eastern Region (MDoNER)",
    problemStatement: "AI-Based Early Warning and Landslide Risk Monitoring System in NER",
    leaderName: "Ayesha Arif Khan",
    rollNo: "251734",
    email: "ayesha.251734.cs@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 37,
    teamName: "Team Claude's Plan",
    mentor: "Asst. Prof. Ahlam Ansari",
    category: "Software",
    psId: "SIH26123",
    hostOrg: "Bharat Electronics Limited",
    problemStatement: "Edge-AI Based Distributed Fleet Coordination for Autonomous Mobile Robots (AMRs) in Smart Warehouses",
    leaderName: "SAKHARKAR SHAAN MISBAH AHMED",
    rollNo: "231244",
    email: "shaan.231244.co@mhssce.ac.in",
    branch: "Computer Engineering",
    status: "Confirmed",
  },
  {
    srNo: 38,
    teamName: "CyberNex",
    mentor: "Ghazala Khan",
    category: "Software",
    psId: "SIH26106",
    hostOrg: "All India Council for Technical Education (AICTE)",
    problemStatement: "AI-Powered Email Threat Detection, GeoLocation and Forensic Intelligence Platform",
    leaderName: "Asad Junaid Badra",
    rollNo: "231808",
    email: "asad.231808.ci@mhssce.ac.in",
    branch: "Computer Science & Engineering (IoT)",
    status: "Confirmed",
  },
  {
    srNo: 39,
    teamName: "RESCUE WINGS",
    mentor: "NASHEET TARIK",
    category: "Hardware",
    psId: "SIH26177",
    hostOrg: "Qualcomm Inc",
    problemStatement: "A deployable AI-powered autonomous drone that aids search-and-rescue operations by detecting people and hazards, thereby improving responder safety and reducing victim discovery time.",
    leaderName: "ALFIYA AFZAL SANDE",
    rollNo: "231742",
    email: "alfiya.231742.cs@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 40,
    teamName: "Team Cocktail",
    mentor: "Nabanita Nath Chowdhury",
    category: "Hardware",
    psId: "SIH26212",
    hostOrg: "AICTE",
    problemStatement: "Student Innovation - Solutions could be in the form of waste segregation, disposal, and improve sanitization system.",
    leaderName: "Ayesha Javed Shaikh",
    rollNo: "242665",
    email: "ayesha.242665.et@mhssce.ac.in",
    branch: "Electronics & Telecommunication Engineering",
    status: "Confirmed",
  },
  {
    srNo: 41,
    teamName: "Thinking Void",
    mentor: "Ahlam Ansari",
    category: "Software",
    psId: "SIH26003",
    hostOrg: "Ministry of Development of North Eastern Region (MDoNER)",
    problemStatement: "AI-Based Cognitive Gaming and Memory Assistance Platform for Elderly Dementia Patients in North Eastern Region (NER)",
    leaderName: "Kazi Zoya Mushtaq",
    rollNo: "251230",
    email: "zoya.251230.co@mhssce.ac.in",
    branch: "Computer Engineering",
    status: "Confirmed",
  },
  {
    srNo: 42,
    teamName: "AMINA",
    mentor: "Dr. Chaitali Mahajan",
    category: "Hardware",
    psId: "SIH26226",
    hostOrg: "AICTE",
    problemStatement: "Student Innovation - Space technology refers to the application of engineering principles to the design, development, manufacture, and operation of devices and systems for space travel and exploration.",
    leaderName: "Shaikh Affan Inayat",
    rollNo: "242774",
    email: "affan.242774.aiml@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Confirmed",
  },
  {
    srNo: 43,
    teamName: "FrontierX6",
    mentor: "Asst. Prof. Ahlam Ansari",
    category: "Software",
    psId: "SIH26032",
    hostOrg: "Ministry of Consumer Affairs, Food & Public Distribution",
    problemStatement: "Farmers often face long waiting times, lack of information regarding procurement schedules, and uncertainty about procurement status.",
    leaderName: "Nusaybah Kazi",
    rollNo: "231215",
    email: "nusaybah.231215.co@mhssce.ac.in",
    branch: "Computer Engineering",
    status: "Confirmed",
  },
  {
    srNo: 44,
    teamName: "GOD'S PLAN",
    mentor: "Dr. Chaitali Mahajan & Er. Awij Alam",
    category: "Hardware",
    psId: "SIH26039",
    hostOrg: "Government of Jharkhand",
    problemStatement: "AI-Powered Underground Mine Safety, Monitoring and Rescue System.",
    leaderName: "Khan Moinuddin Jamal Ahmed",
    rollNo: "241624",
    email: "moinuddin.241624.et@mhssce.ac.in",
    branch: "Electronics & Telecommunication Engineering",
    status: "Confirmed",
  },
  {
    srNo: 45,
    teamName: "Team Precognix",
    mentor: "Dr. Ashfaq Sir",
    category: "Software",
    psId: "SIH26153",
    hostOrg: "National Technical Research Organisation (NTRO)",
    problemStatement: "AI based network attack forecasting from network traffic data",
    leaderName: "IFFAT ANEES ANSARI",
    rollNo: "231404",
    email: "iffat.231404.it@mhssce.ac.in",
    branch: "Information Technology",
    status: "Confirmed",
  },
];

export const SIH_WAITING_DATA = [
  {
    srNo: 1,
    teamName: "Jonaki",
    mentor: "Dr. Chaitali Mahajan",
    category: "Software",
    psId: "SIH26003",
    hostOrg: "Ministry of Development of North Eastern Region (MDoNER)",
    problemStatement: "AI-Based Cognitive Gaming and Memory Assistance Platform for Elderly Dementia Patients in North Eastern Region (NER)",
    leaderName: "Hajra Khan",
    rollNo: "252764",
    email: "hajra.252764.cs@mhssce.ac.in",
    branch: "Computer Science & Engineering (AIML)",
    status: "Waiting List",
  },
  {
    srNo: 2,
    teamName: "CtrlAltEcho",
    mentor: "Dr. Ashfaq Shaikh",
    category: "Software",
    psId: "SIH26104",
    hostOrg: "All India Council for Technical Education (AICTE)",
    problemStatement: "AI-Powered Real-Time Detection and Prevention of Voice Cloning Impersonation Attacks",
    leaderName: "Khomosi Yusuf Murtuza",
    rollNo: "241231",
    email: "yusuf.241231.co@mhssce.ac.in",
    branch: "Computer Engineering",
    status: "Waiting List",
  },
  {
    srNo: 3,
    teamName: "KisanCore",
    mentor: "Awij shaikh",
    category: "Hardware",
    psId: "SIH26005",
    hostOrg: "Ministry of Development of North Eastern Region (MDoNER)",
    problemStatement: "Solar-Powered Smart Mini Cold Storage System for Fresh Vegetables in North Eastern Region (NER)",
    leaderName: "Sayyed Mohammed Abbas",
    rollNo: "241644",
    email: "abbas.241644.et@mhssce.ac.in",
    branch: "Electronics & Telecommunication Engineering",
    status: "Waiting List",
  },
  {
    srNo: 4,
    teamName: "Pluto",
    mentor: "Farhana Siddiqui",
    category: "Software",
    psId: "SIH26132",
    hostOrg: "Government of Maharashtra",
    problemStatement: "Strengthening market linkages and price discovery for farmers",
    leaderName: "Gargi Unhalekar",
    rollNo: "241261",
    email: "gargi.241261.co@mhssce.ac.in",
    branch: "Computer Engineering",
    status: "Waiting List",
  },
  {
    srNo: 5,
    teamName: "CareForge",
    mentor: "Fardeen Sheikh",
    category: "Software",
    psId: "SIH2607",
    hostOrg: "Ministry of Ayush",
    problemStatement: "Patient Case-Taking Software",
    leaderName: "Prem Pagar",
    rollNo: "251928",
    email: "prem.251928.ci@mhssce.ac.in",
    branch: "Computer Science & Engineering (IoT)",
    status: "Waiting List",
  },
];

export const SIH_ALL_RESULTS = [
  ...SIH_CONFIRMED_DATA,
  ...SIH_WAITING_DATA,
];
